### ISSUE TITLE
Виджет глючит

### ISSUE THREAD

**Issue by sashabeep** [extras-evolution/MultiFiles#1]
Не жает выбрать файл и заполнить описание. При клике на виджете показывает полупрозрачную копию поля ввода. Modx 1.1, плагин из Extras
![bug](http://i.imgur.com/oP6l1ll.gif)

**Comment by Dmi3yy** [comment]
Проще всего использовать  multiTV для ваших целей:) 
давно не проверял мильтиФото и файлы
